universe = vanilla
executable = cluster/run_condor_archive_job.sh
initialdir = .

arguments = $(job_id)

log = cluster/log/$(job_id).log
output = cluster/out/$(job_id).out
error = cluster/error/$(job_id).err

request_cpus = 1
request_memory = $(request_memory)
request_disk = 2GB
rank = Memory

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = cluster/condor_payload.tar.gz
transfer_output_files = results

queue job_id, request_memory from (
  small_s7, 1500MB
  small_s17, 1500MB
  small_s29, 1500MB
)
